# Generated by Django 2.0.5 on 2019-06-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'usertable',
            },
        ),
    ]
