# Generated by Django 2.0.5 on 2019-07-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190701_1130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindb',
            table='logintable',
        ),
    ]
