# Generated by Django 2.0.5 on 2019-07-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190702_1022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindb',
            table=None,
        ),
    ]
